backuppc/backuppc

- bin/BackupPC_dump
- lib/BackupPC/Xfer/Smb.pm
Fixing compatibility with Samba 4.3 with some hockery-pockery with logic. Please review and merge if possible.
Fixes #21
> Fixing compatibility with Samba 4.3

- bin/BackupPC_dump
> Revert "V4.0.0"

- bin/BackupPC_dump
> Remove the full fsck that was intended for testing

- bin/BackupPC_dump
> Revert "Revert "V4.0.0""

- images/BackupPC_modern.css
This is a new CSS style sheet proposal, using modern visual styles and bigger fonts at consistent sizes.
It works on BackupPC 3.3 and 4.0 (you only need to change $Conf{CgiCSSFile} = 'BackupPC_modern.css'; in config.pl to use it).
> Modern theme

- configure.pl
> Revert "configure.pl: Remove extra quotes from $Conf{CgiURL}"

- conf/config.pl
- configure.pl
Infact, https://github.com/backuppc/backuppc/pull/80 was correct but just incomplete.
> configure.pl: Finally remove extra quotes from $Conf{CgiURL}

- bin/BackupPC
- bin/BackupPC_archive
- bin/BackupPC_restore
- bin/BackupPC_tarCreate
- bin/BackupPC_tarExtract
- bin/BackupPC_zipCreate
- conf/config.pl
- lib/BackupPC/Lib.pm
- lib/BackupPC/Xfer.pm
- lib/Net/FTP/AutoReconnect.pm
patch contains some spelling fixes ( just in comments ) as found by a bot ( http://www.misfix.org, https://github.com/ka7/misspell_fixer ). Any upcoming License changes (e.g. GPL2 to GPL3+) are hereby granted.
> spelling fixes

- lib/BackupPC/Lang/de.pm
its E-Mail in German, not eMail: http://www.duden.de/rechtschreibung/E_Mail
> Typo correction

- lib/BackupPC/Lang/it.pm
> Fix some italian translations

- bin/BackupPC
@craigbarratt , Probably it's time to update versions of dependencies as well.
> Fix BackupPC::XS min version in error message

- .travis.yml
- cpanfile
for simple build and run test
@craigbarratt To enable Travis CI builds for the repository, please follow these links:
https://github.com/marketplace/travis-ci
https://docs.travis-ci.com/user/getting-started/
> [CI] Add Travis CI configuration

- bin/BackupPC
- bin/BackupPC_Admin_SCGI
- cgi-bin/BackupPC_Admin
- lib/BackupPC/CGI/DeleteBackup.pm
- lib/BackupPC/CGI/HostInfo.pm
- lib/BackupPC/Lang/cz.pm
- lib/BackupPC/Lang/de.pm
- lib/BackupPC/Lang/en.pm
- lib/BackupPC/Lang/es.pm
- lib/BackupPC/Lang/fr.pm
- lib/BackupPC/Lang/it.pm
- lib/BackupPC/Lang/ja.pm
- lib/BackupPC/Lang/nl.pm
- lib/BackupPC/Lang/pl.pm
- lib/BackupPC/Lang/pt_br.pm
- lib/BackupPC/Lang/ru.pm
- lib/BackupPC/Lang/uk.pm
- lib/BackupPC/Lang/zh_CN.pm
- makeDist
BTW, I have no idea what version number I should put in the module's header.
> [Feature] Add ability to delete backups using CGI

- conf/sorttable.js
- lib/BackupPC/CGI/HostInfo.pm
- lib/BackupPC/Lang/cz.pm
- lib/BackupPC/Lang/de.pm
- lib/BackupPC/Lang/en.pm
- lib/BackupPC/Lang/es.pm
- lib/BackupPC/Lang/fr.pm
- lib/BackupPC/Lang/it.pm
- lib/BackupPC/Lang/ja.pm
- lib/BackupPC/Lang/nl.pm
- lib/BackupPC/Lang/pl.pm
- lib/BackupPC/Lang/pt_br.pm
- lib/BackupPC/Lang/ru.pm
- lib/BackupPC/Lang/uk.pm
- lib/BackupPC/Lang/zh_CN.pm
Hi,
As discuss in issue https://github.com/backuppc/backuppc/issues/199, I propose this pull request to change HostInfo table rows order and globally make tables sortable on interface.
To do that, I made some improvements on _sortable.js_ lib and principally add CSS classes in translations files.
Regards,
Benjamin
> Table order and sortable

- backuppc.css
when jump using hyperlinks (e.g. from TOC)
> Fix headers hiding below nav menu

- bin/BackupPC
- bin/BackupPC_fsck
@craigbarratt , @ldrolez Would you please explain, why do we open `STDIN` for output?
> Fix warnings: bin/BackupPC

- bin/BackupPC
- bin/BackupPC_fsck
> Remove unused counters of renamed files

- lib/BackupPC/Lang/pl.pm
I fixed typos and a little changed phrasing to make it more clear what is going on.
> Improve polish translation (v3.x.x)

- lib/BackupPC/Lang/fr.pm
This translates the unique PleaseTranslateThis flag for french
> Translate the PleaseTranslateThis flag for french

- lib/BackupPC/CGI/EditConfig.pm
Fixing the layout of the hosts table in the main configuration editor in the CGI-interface
> Hosts table layout fixed

- bin/BackupPC
just for code readability, see #278
> Fix STDIN open mode

- httpd/src/BackupPC.conf
> Make configuration file compatible with Apache 2.4+

- bin/BackupPC_rrdUpdate
> Avoid RRD updates using the same time stamp

- doc-src/BackupPC.pod
Add nginx sample configuration file with S/CGI
> [docs] Add nginx sample config

- lib/BackupPC/CGI/EditConfig.pm
> Increase maximum length of configuration editor fields

- .travis.yml
Speed up linting process a bit by caching pip packages
> Cache pip packages in Travis CI

- lib/BackupPC/Lang/pl.pm
This is continuation of https://github.com/backuppc/backuppc/pull/286. I applied same changes to the file `pl.pm` on master branch. Unfortunately I do not have running instance of backuppc v4 to test it.
> Improve polish translation (v4)

- lib/BackupPC/CGI/Metrics.pm
This fixes several warnings : 
```
BackupPC_Admin: Variable "%poolMapper" will not stay shared at /usr/local/BackupPC/lib/BackupPC/CGI/Metrics.pm line 98.
BackupPC_Admin: "my" variable $hostState masks earlier declaration in same scope at /usr/local/BackupPC/lib/BackupPC/CGI/Metrics.pm line 226.
BackupPC_Admin: "my" variable $hostLastAttempt masks earlier declaration in same scope at /usr/local/BackupPC/lib/BackupPC/CGI/Metrics.pm line 227.
BackupPC_Admin: "my" variable $hostDisabled masks earlier declaration in same scope at /usr/local/BackupPC/lib/BackupPC/CGI/Metrics.pm line 228.
BackupPC_Admin: Use of uninitialized value in numeric le (<=) at /usr/local/BackupPC/lib/BackupPC/CGI/Metrics.pm line 292.
BackupPC_Admin: Use of uninitialized value in string eq at …
```
> fixes metrics.pm warnings

- lib/BackupPC/CGI/Metrics.pm
Signed-off-by: Pierre Belloy <p.belloy@axelor.com>
> Fixes prometheus metrics when value is an array

- doc-src/BackupPC.pod
Signed-off-by: Raoul Bhatia <raoul@bhatia.at>
Supersedes #366
> Fix typo in pool layout description

- doc-src/BackupPC.pod
Included a bit of the documentation from sourceforge to git
> modified BackupPC.pod to include security and limitations from sourceforge

- conf/BackupPC_mod.css
fresh look for standard theme.
> some tweaks for current theme

- lib/BackupPC/CGI/AdminOptions.pm
- lib/BackupPC/CGI/Archive.pm
- lib/BackupPC/CGI/ArchiveInfo.pm
- lib/BackupPC/CGI/Browse.pm
- lib/BackupPC/CGI/DeleteBackup.pm
- lib/BackupPC/CGI/DirHistory.pm
- lib/BackupPC/CGI/EditConfig.pm
- lib/BackupPC/CGI/EmailSummary.pm
- lib/BackupPC/CGI/GeneralInfo.pm
- lib/BackupPC/CGI/HostInfo.pm
- lib/BackupPC/CGI/LOGlist.pm
- lib/BackupPC/CGI/Lib.pm
- lib/BackupPC/CGI/Queue.pm
- lib/BackupPC/CGI/Restore.pm
- lib/BackupPC/CGI/RestoreInfo.pm
- lib/BackupPC/CGI/StartStopBackup.pm
- lib/BackupPC/CGI/Summary.pm
- lib/BackupPC/CGI/View.pm
to extend CSS
https://github.com/backuppc/backuppc/pull/372#issuecomment-701235297
<div id="Content">
as requested by @sergeyklochko in private communication.
> Add classes to "Content" div

- lib/BackupPC/CGI/EditConfig.pm
> Add classes to configuration editor settings table (#378)

- bin/BackupPC_sendEmail
- conf/config.pl
- doc-src/BackupPC.pod
- lib/BackupPC/CGI/EditConfig.pm
- lib/BackupPC/Config/Meta.pm
> add sendmailArgs to code

- doc-src/BackupPC.pod
Accordingly to https://tracker.debian.org/pkg/backuppc there are new Debian package maintainer.
> New Debian maintainer

- configure.pl
which also fixes install target file names
> Refactor CSS installation

- bin/BackupPC_archiveHost
Fixes https://github.com/backuppc/backuppc/issues/463
> Clean stdout and support writing to a pipe
