backuppc/backuppc

- lib/BackupPC/CGI/EditConfig.pm
Since Perl 5.18, the order of hash keys is always randomized, leading to
moving columns across page refreshes.
> [Minor] Fix random tab order in EditConfig

- bin/BackupPC_sendEmail
This resolves #3.
The checks for per-host warning messages overwrite the configuration with that of the individual hosts. As a result, the email regarding bad hosts is sent to the `EMailAdminUserName` of the last host that is checked (leading to #3). This change fixes the configuration overwrite and sends separate emails regarding bad hosts to their respective admins.
> Bugfix: admin email overwrite in sendEmail

- lib/BackupPC/Lib.pm
[perl5200delta](http://search.cpan.org/dist/perl-5.22.0/pod/perldelta.pod#A_literal_%22{%22_should_now_be_escaped_in_a_pattern)
> [Minor] Escape "{" literal in regexps

- bin/BackupPC_dump
- bin/BackupPC_restore
- conf/config.pl
- configure.pl
- lib/BackupPC/CGI/EditConfig.pm
- lib/BackupPC/Config.pm
- lib/BackupPC/Config/Meta.pm
- lib/BackupPC/Lib.pm
This PR adds support for IPv6.
To support IPv6, there are basically 2 changes required:
1. Replace gethostbyname() - which works for IPv4 only - with similar functionality of Socket::getaddrinfo()
2. Some environments require the use of a different ping binary for IPv6 hosts.
The second change is implemented by introducing an additional config variable named PingPath6 which can be set to something like '/usr/bin/ping6' in such environments. For modern environments like Fedora, this can be set to /usr/bin/ping, because their standard ping supports both IPv4 and IPv6.
Cheers
-Fritz
> Add support for IPv6

- lib/BackupPC/Xfer/Smb.pm
RestoreLOG sample:
```
tarCreate: Done: 1 files, 39 bytes, 0 dirs, 0 specials, 0 errors
tconx ok
tar:316  tarmode is now full, system, hidden, noreset, quiet
tar:1052 +++ ./+/test/2 - Copy.txt
tar:632  tar_process done, err = 0
restore failed: tar:632  tar_process done, err = 0
```
> Fix result for restore using Samba4

- README.md
Fixes #49 
This commit takes the README into the 21st century :) Long live BackupPC!
Mainly, this PR converts the README to Markdown format. I also replaced some references to SourceForge with GitHub (although there are still some references for the documentation to SourceForge) and I moved the license to the bottom of the file (that is the most common place to put the license, at least what I have seen).
Anything more that should be changed/added, or should some changes be reverted?
If you want to see how the new README looks like, have a look at https://github.com/ehannes/backuppc/tree/markdown.
> Fixes #49 Converts README to Markdown format

- configure.pl
This adds ability to skip installation phase and intended for using mostly
by packagers. It is assumed that the OS distribution package should install
configure.pl somewhere and provide a wrapper script for users like:
```sh
#!/bin/sh
PERL5LIB=/usr/local/lib
perl %%PREFIX%%/libexec/backuppc/configure.pl \
--config-only
--bin-path perl=%%PREFIX%%/bin/perl \
--config-dir %%ETCDIR%% \
--cgi-dir %%CGIDIR%% \
--data-dir /var/db/BackupPC \
--fhs \
--html-dir %%WWWDIR%% \
--html-dir-url /backuppc \
--install-dir %%PREFIX%% \
--log-dir /var/log/BackupPC
```
> configure.pl: Introduce --config-only option (#15)

- bin/BackupPC_dump
Proposed pull request fixes full backup expire exponential algorithm. Current algorithm has issues with backups loss after modifying configuration settings or making manual backups.
**A thorough review (not just LGTM) is required for this pull-request.**
Both v3 and v4 are affected. Pull requests are opened for both `master` and `v4.0.0` branches.
Explanation with some examples:
https://gist.github.com/moisseev/d5a8a499a7b69b1f0428#comment-1442896
Test script to play with:
https://gist.github.com/moisseev/d5a8a499a7b69b1f0428
It a simple wrapper for `BackupPC_dump` subroutines: `BackupExpire` and `BackupFullExpire`.
> [CritFix] Change full backup expire algorithm to aviod data loss

- systemd/src/init.d/gentoo-backuppc
/sbin/runscript has been deprecated, /sbin/openrc-run is now recommended.
--chuid is also deprecated
--group is useful, although it is currently the same as USER (maybe this should be changed across BPC)
> Improvement for Gentoo init script

- configure.pl
If the $Conf{CgiURL} is missed in the config.pl somehow, the configure.pl
creates it on upgrade like `$Conf{CgiURL} = ''http... ''`.
That breaks config.pl.
> configure.pl: Remove extra quotes from $Conf{CgiURL}

- systemd/src/init.d/gentoo-backuppc
the parent of BPC pid must exist and be writable by the BPC user, otherwise the service fails to start with OpenRC. This fixes it.
> minor improvement for openrc init script

- configure.pl
The hard-coded /etc/BackupPC directory breaks existing config file check
for filesystem hierarchies with specific config directories like /usr/local/etc
> Search --config-dir for existing config file

- bin/BackupPC_dump
- bin/BackupPC_restore
- conf/config.pl
We use backuppc a lot but we are missing one feature.
We have a lots of laptop which connect randomly on wired connections or on wireless connections.
We try advanced DNS stuff but were unable to have a decent result.
Thus we made this patch.
Similar to ClientNameAlias, we implemented ClientWifiAlias.
What does it do ?
Instead a fetching a unique hostIP, we build an array of valid IP and loop on them.
I know it's far from being ready to merge but I'd like feedback on how to improve it :
- ClientWifiAlias : maybe make this an array ? or a better name ?
Cheers,
> feat(ClientWifiAlias): added an extra parameters to allow wifi backup

- bin/BackupPC_dump
When FixedIPNetBiosNameCheck is falsey then this condition should
match regardless if host == hostIP or not.
> Fix the condition to prevent netbios name check

- conf/config.pl
* `zh_CH`: Chinese in Switzerland
* `zh_CN`: Chinese in China
`zh_CN` is the code actually used in BackupPC: https://github.com/backuppc/backuppc/blob/master/lib/BackupPC/Lang/zh_CN.pm
> Fix incorrect language code in config comments: zh_CH → zh_CN

- bin/BackupPC
printf is required to log version of Perl 5.8
https://perldoc.perl.org/perlvar.html#%24^V
> Increase start-up message verbosity

- systemd/README
`/usr/lib` is supposed to be managed by the distribution's package manager.
> Custom service files belong in `/etc/systemd/system`

- conf/config.pl
SMBclient defaults to NT1 (SMB1) unless the user specifies a higher version. See the documentation of `smbclient`:
```
-m|--max-protocol protocol
This allows the user to select the highest SMB protocol level that smbclient will use to connect to the server. By default this is
set to NT1, which is the highest available SMB1 protocol. To connect using SMB2 or SMB3 protocol, use the strings SMB2 or SMB3
respectively. Note that to connect to a Windows 2012 server with encrypted transport selecting a max-protocol of SMB3 is required.
```
I've tested the patch with a synology NAS (DSM6.1). This offers an option to specify the minimum SMB-version, that defaults to SMB1. Changing the configuration to SMB2, backuppc is unable to connect. (`Got fatal error during xfer (protocol negotiation failed: …
> Remove SMB1 restriction

- bin/BackupPC
Latest version of rsync-bpc broke BackupPC, with the following error message:
```
BackupPC: rsync_bpc at /usr/local/bin/rsync_bpc needs to be upgraded (got version ; need >= 3.0.9.8); exiting in 30s
```
Indeed, `/usr/local/BackupPC/bin/BackupPC` will run at startup `rsync_bpc --version` at startup to check if a sufficiently up-to-date version is used.
To check the version, BackupPC will use this following regex (line 124):
```
/rsync_bpc\s+version\s+([\d.]+?)(\.beta\d+)?\s+protocol/
```
This regex is able to match a version like `3.1.2` or `3.1.2.beta0`. However, version 3.0.9.13 of rsync-bpc will return `3.1.2beta0`. Notice the absence of dot before `beta0`. So the version is not matched, and BackupPC hangs up.
This PR fixes that by replacing the faulty regex with this one:
``` …
```
> Fix BackupPC when rsync-bpc 3.1.2beta0 is used

- doc-src/BackupPC.pod
When using SCGI connection, the perl module SCGI is required.
This PR will add the requirement in the requirements section
> [docs] Add SCGI perl module as requirements for S/CGI connection

- lib/BackupPC/Xfer/Tar.pm
FreeBSD/pfsense's tar outputs a slightly different format, making BackupPC think that no files were dumped, when in fact they were.
GNU tar: `./newfile.txt`
FreeBSD tar: `a ./newfile.txt`
More details and credits to Sebastiaan van Erk: https://sourceforge.net/p/backuppc/mailman/message/34909672/
> Make tar Xfer compatible with FreeBSD tar

- .perltidyrc
- .travis.yml
This change will print a git diff if the pre-commit hooks are failing. Helping us to spot where the problems are.
> Add pre-commit --diff-on-failure in Travis CI

- .perltidyrc
- lib/BackupPC/Lang/ja.pm
- lib/BackupPC/Lang/zh_CN.pm
Fixed perltidy formatting and added an extra iteration for perltidy to be sure we reach the proper state in one perltidy run.
I fixed the formatting using `pre-commit run --all`
> Fix perltidy formating

- doc-src/BackupPC.pod
Parameters in the URL should be separated by ampersands.
> Fix metrics URLs in doc

- lib/BackupPC/CGI/Metrics.pm
When a a host doesn't have an incremental backup the prometheus metric eported resulted in an metric line without a value.
> Prevent incrDuration metric value being undefined

- conf/config.pl
When rsync over ssh crosses a firewall (which is fairly often) and a large file is being processed, rsync can take quite some time calculating the hash values for all chunks in the file. During this time the ssh connection sits idle and this can cause the firewall to forget all about the connection and drop it. To resolve this ssh can send a NULL packet ever so often to keep the connection alive.
It gave us major headaches to find the root cause of this problem. Please consider adding this to the default backuppc config.pl
> Add ServerAliveInterval to $Conf{RsyncSshArgs}

- doc-src/BackupPC.pod
- lib/BackupPC/CGI/Metrics.pm
I am working on a Zabbix template for BackupPC. I have made some small improvements to the JSON output.
I have replaced the full/incr_age with *_start_time as the variable did not report "age".
Added few more backup statistics to output and tried to optiimze the detection of the last full and incremental backup in metrics code.
This fixes
https://github.com/backuppc/backuppc/issues/387
and to some degree
https://github.com/backuppc/backuppc/issues/388
PS. Hopefully I did not break anything, but please review carefully :)
> Metrics additions and change full/inc_age with full/incr_start_time

- .circleci/config.yml
- .gitignore
- .tidyallrc
- build test
- podchecker
Now Travis CI tests are waiting in the queue about half an hour before starting the build. It is too long. CircleCI is faster and it's queue times are minimal.  Testing various Perl versions in CircleCI is complicated, so I propose to keep it in Travis CI since Travis CI supports Perl natively.
I've created CircleCI configuration for one build test on preinstalled Perl version and `podchecker` test. I am planning to add `podtidy`, `Test::Vars` and move `pre-commit` tests from Travis CI.
I've  used `tidyall` to run `podchecker` just because I am not familiar with `pre-commit` (I guess we should write own hook for `podchecker`) but with `tidyall` it is simple and straightforward .
> [Test] Add CircleCI tests

- .circleci/config.yml
- .tidyallrc
- configure.pl
- doc-src/BackupPC.pod
- lib/Net/FTP/AutoReconnect.pm
- lib/Net/FTP/RetrHandle.pm
@craigbarratt To use `thekevjames/linter` orb on CircleCI you need to allow using third party orbs in `Organization Settings / Security`.
Now we can disable Travis tests completely. You can turn off builds for the repo in the repositories list on Travis account page. Deleting or changing `.travis.yml` file is not necessary.
> [Test] CircleCI: Build on multiple Perl versions and add pre-commit job

- lib/BackupPC/CGI/Metrics.pm
as described in https://github.com/backuppc/backuppc/issues/403
Update Metrics.pm to prevent error:
`expected value after metric, got "MNAME"`
> Prometheus scraping error Issue #403

- BackupPC.html
The example URLs for presenting different types of metrics used a `?` rather than a `&` to pass the metric type, which does not work.
Should hopefully save someone else some confusion time :)
> Docs bug in metrics links
